"""add paid_at to fee_records

Revision ID: 16190d489c2e
Revises: bc171edb179e
Create Date: 2026-02-20 17:53:17.329622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16190d489c2e'
down_revision: Union[str, Sequence[str], None] = 'bc171edb179e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_records', sa.Column('paid_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_records', 'paid_at')
    # ### end Alembic commands ###
