"""belt grade as string with active belt grades table

Revision ID: 5ae629450a35
Revises: 5fad9e5c0f89
Create Date: 2026-02-19 18:56:49.669653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae629450a35'
down_revision: Union[str, Sequence[str], None] = '5fad9e5c0f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('active_belt_grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade')
    )
    op.create_index(op.f('ix_active_belt_grades_id'), 'active_belt_grades', ['id'], unique=False)

    # Use raw SQL to avoid SQLAlchemy recreating the enum
    op.execute("""
        CREATE TABLE role_promotions (
            id SERIAL NOT NULL,
            user_id INTEGER NOT NULL,
            promoted_by INTEGER NOT NULL,
            old_role userrole NOT NULL,
            new_role userrole NOT NULL,
            branch_id INTEGER NOT NULL,
            created_at TIMESTAMP WITHOUT TIME ZONE,
            PRIMARY KEY (id),
            FOREIGN KEY(branch_id) REFERENCES branches (id),
            FOREIGN KEY(promoted_by) REFERENCES users (id),
            FOREIGN KEY(user_id) REFERENCES users (id)
        )
    """)
    op.create_index(op.f('ix_role_promotions_id'), 'role_promotions', ['id'], unique=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_promotions_id'), table_name='role_promotions')
    op.drop_table('role_promotions')
    op.drop_index(op.f('ix_active_belt_grades_id'), table_name='active_belt_grades')
    op.drop_table('active_belt_grades')
    # ### end Alembic commands ###
