"""add paid_date to offline payment requests

Revision ID: 8967f7b0e5e9
Revises: 16190d489c2e
Create Date: 2026-02-20 18:03:38.053053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8967f7b0e5e9'
down_revision: Union[str, Sequence[str], None] = '16190d489c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offline_payment_requests', sa.Column('paid_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offline_payment_requests', 'paid_date')
    # ### end Alembic commands ###
