"""make parent and emergency contact optional

Revision ID: bc171edb179e
Revises: c4343fae9a25
Create Date: 2026-02-20 16:26:36.341892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc171edb179e'
down_revision: Union[str, Sequence[str], None] = 'c4343fae9a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('students', 'emergency_contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'emergency_contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('students', 'parent_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
