"""add triggered_by to notifications

Revision ID: c4343fae9a25
Revises: 91532e5a7694
Create Date: 2026-02-19 23:50:35.809571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4343fae9a25'
down_revision: Union[str, Sequence[str], None] = '91532e5a7694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('triggered_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'users', ['triggered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'triggered_by')
    # ### end Alembic commands ###
