"""add payment_type to offline requests

Revision ID: ee12f26e6ed6
Revises: 8967f7b0e5e9
Create Date: 2026-02-23 13:10:11.530317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee12f26e6ed6'
down_revision: Union[str, Sequence[str], None] = '8967f7b0e5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offline_payment_requests', sa.Column('payment_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offline_payment_requests', 'payment_type')
    # ### end Alembic commands ###
